@startuml Diagrama_de_Clases_Novus
hide circles
hide empty members
title Diagrama de Clases de Plataforma Novus - Gestión de Becarios PROFER

skinparam {
    ClassBackgroundColor #f0f8ff
    ClassBorderColor #4682b4
    ClassFontColor #000000
    ClassFontSize 14
    ClassAttributeFontColor #191970
    ClassAttributeFontSize 12
}
' Definición de clases principales

class PLATAFORMA {

}

abstract class USUARIO {
}

class POSTULANTE {
}

class BECARIO {

}

class ADMINISTRADOR {

}

class TEST {

}

class CAPACITACION {

}

class CONTENIDO_CAPACITACION {

}

class VIDEO_TUTORIAL {

}

class DOCUMENTACION {

}

class ESTADISTICA {

}

class SELECCIONADOR {

}

PLATAFORMA  -->  ESTADISTICA : "genera"
PLATAFORMA  -->  USUARIO : "gestiona"
PLATAFORMA  -->  TEST : "incluye"
PLATAFORMA  -->  CAPACITACION : "ofrece"

USUARIO <|-- ADMINISTRADOR
USUARIO <|-- POSTULANTE
USUARIO <|-- SELECCIONADOR
POSTULANTE <|-- BECARIO : "se convierte si\naprueba tests"

ADMINISTRADOR --> PLATAFORMA : "administra"
ADMINISTRADOR --> CAPACITACION : "gestiona"
ADMINISTRADOR --> ESTADISTICA : "consulta"

SELECCIONADOR --> ESTADISTICA : "consulta"

CAPACITACION  -->  CONTENIDO_CAPACITACION : "contiene"
CONTENIDO_CAPACITACION <|-- VIDEO_TUTORIAL
CONTENIDO_CAPACITACION <|-- DOCUMENTACION

POSTULANTE -->  TEST : "realiza"
TEST --> BECARIO : "aprobación\nconvierte en"

USUARIO  -->  CAPACITACION : "accede a"

@enduml
