@startuml Diagrama_de_Clases_Beca

hide empty members
hide circle


class PLATAFORMA {
  Novus 
}

class ESTADÍSTICA {
}

abstract class USUARIO {
}

class ADMINISTRADOR {
}

class PRUEBAS {
}

class CAPACITACIÓN {
}

class POSTULANTE {
}

class CONTENIDOS {
}


PLATAFORMA --> ESTADÍSTICA : "genera"
PLATAFORMA <--- USUARIO : "accede a"
PLATAFORMA --> PRUEBAS : "incluye"
PLATAFORMA --> CAPACITACIÓN : "ofrece"

USUARIO <|-- ADMINISTRADOR
ADMINISTRADOR --> PLATAFORMA : "administra"

CAPACITACIÓN --> CONTENIDOS : "contiene"
USUARIO <|-- POSTULANTE
@enduml
