@startuml
title Detallado del Crear Test

start

:VISTA_CREAR_TEST;

partition ManejoCrearTest {
  
  :Administrador solicita introducir información básica
  • Nombre del test
  • Descripción
  • Duración límite
  • Puntaje máximo;

  :Sistema permite introducir los datos;
  
  repeat
    :Administrador solicita configurar pregunta
    • Define tipo: múltiple opción/abierta
    • Asigna puntaje por pregunta
    • Establece respuestas correctas;

    :Sistema permite configurar pregunta;
    
    :Sistema valida la configuración
    • Suma de puntajes = puntaje máximo
    • La pregunta tiene respuesta;
  repeat while (¿Crear otra pregunta?) is (Sí)
  ->No;
  
  :Sistema crea el test;
    
 :Sistema muestra
 • Mensaje: "Test creado exitosamente";
    

  
}

stop
@enduml