@startuml
title Detallado del Crear Postulante

start

:VISTA_CREAR_POSTULANTE;

partition ManejoCrearPostulante {
  
  :Administrador solicita introducir datos del postulante;

  :Sistema permite introducir los datos;
  
  if (¿Datos válidos?) then (No)
    :Sistema muestra
    • Error: "Datos inválidos";
   
  
    
  else (Sí)
    if (¿Usuario ya existe?) then (Sí)
      :Sistema muestra
      • Error: "Usuario ya registrado"
      • Opción: "Ver perfil existente";
      
    else (No)
      :Sistema crea el usuario;
      
      :Sistema muestra
      • Mensaje: "Postulante creado exitosamente"
      • Redirige a perfil del postulante;
      
    endif
    
  endif
  
}

stop
@enduml