@startuml
title Detallado del Editar Postulante

start

:VISTA_EDITAR_POSTULANTE;

partition ManejoEditarPostulante {
  
  :Sistema muestra datos existentes;
  
  if (¿Postulante existe?) then (No)
    :Sistema muestra
    • Error: "Postulante no encontrado";
    
  else (Sí)
    :Administrador solicita modificar información;
    
    :Sistema permite modificar información;
    
    :Sistema valida cambios
    • Integridad de datos;
    
    if (¿Datos válidos?) then (No)
      :Sistema muestra
      • Error: "Datos inválidos";
      
    else (Sí)
        :Sistema actualiza postulante;
        
        :Sistema muestra
        • Mensaje: "Postulante actualizado"
        • Resumen de cambios realizados;
      
      
    endif
    
  endif
  
}

stop
@enduml