@startuml
title Detallado del Eliminar Capacitación

start

:VISTA_ELIMINAR_CAPACITACION;

partition ManejoEliminarCapacitacion {
  
  :Administrador selecciona capacitación;

  :Administrador solicita eliminar capacitación;
  
  :Sistema muestra confirmación
  • Pregunta: "¿Está seguro?"
  • Detalles de la capacitación;
    
    if (¿Administrador confirma?) then (No)
      :Sistema cancela operación;
      
    else (Sí)
      :Sistema elimina capacitación;
      
      :Sistema muestra
      • Mensaje: "Capacitación eliminada"
      • Actualiza lista;
      
    endif
    
  
  
}

stop
@enduml