@startuml
title Detallado del Listar Postulante

start

:VISTA_LISTAR_POSTULANTE;

partition ManejoListarPostulante {

  :Administrador/seleccionador solicita ver los postulantes;
  
  :Sistema muestra los postulantes;
  
  if (¿Existen postulantes?) then (No)
    :Sistema muestra
    • Mensaje: "No hay postulantes registrados";
    
    
  else (Sí)
    :Sistema muestra lista;
    
    :Administrador selecciona acción disponible
    • Ver perfil completo
    • Editar información
    • Eliminar postulante;
    
    :Sistema procesa la acción elegida
    • Ver: muestra información completa
    • Editar: redirige a formulario
    • Eliminar: solicita confirmación;
    
  endif
  
}

stop
@enduml