@startuml
title Detallado del Listar Capacitación

start

:VISTA_LISTAR_CAPACITACION;

partition ManejoListarCapacitacion {

  :Usuario solicita ver las capacitaciones;
  
  :Sistema muestra las capacitaciones;
  
  if (¿Existen capacitaciones?) then (No)
    :Sistema muestra
    • Mensaje: "No hay capacitaciones disponibles";
    
  else (Sí)
    :Sistema muestra lista de capacitaciones;
    
  endif
  
}

stop
@enduml