@startuml
title Detallado del Listar Postulante

start

:VISTA_LISTAR_POSTULANTE;

partition ManejoListarPostulante {
  
  :Sistema carga los postulantes
  • Consulta base de datos
  • Aplica filtros por defecto
  • Paginación automática;
  
  if (¿Existen postulantes?) then (No)
    :Sistema muestra
    • Mensaje: "No hay postulantes registrados"
    • Opción para crear nuevo;
    
    
  else (Sí)
    :Sistema muestra lista
    • Nombre Completo, email, pasaporte, direccion,contraseña 
    • Estado del postulante
    • Fecha de registro
    • Opciones: Ver/Editar/Eliminar;
    
    
    
    :Administrador selecciona acción disponible
    • Ver perfil completo
    • Editar información
    • Eliminar postulante;
    
    :Sistema procesa la acción elegida
    • Ver: muestra información completa
    • Editar: redirige a formulario
    • Eliminar: solicita confirmación;
    
  endif
  
}

stop
@enduml