@startuml
title Detallado del Ver Estadísticas

start

:VISTA_ESTADISTICAS;

partition ManejoVerEstadisticas {
  
  :Administrador/Seleccionador solicita acceder al módulo
  • Selecciona "Estadísticas";

  :Sistema permite acceder al módulo;
  
  if (¿Datos disponibles?) then (No)
    :Sistema muestra
    • Error: "No hay datos suficientes";
    
  else (Sí)
    :Sistema genera estadísticas;
    
    :Sistema muestra dashboard;

    :Administrador/seleccionador solicita exportar;

    :Sistema permite exportación;
    
    if (¿Usuario exporta?) then (Sí)
      :Sistema genera reporte;
      
    else (No)
      :Administrador/seleccionador continúa navegando;
      
    endif
    
  endif
  
}

stop
@end