@startuml
title Detallado del Ver Progreso

start

:VISTA_VER_PROGRESO;

partition ManejoVerProgreso {
  
  :Postulante/Becario solicita acceder a su dashboard
  • Autenticación verificada
  • Carga perfil de usuario;
  
  :Sistema permite acceder a su dashboard;
  
  :Sistema consulta datos de progreso;
  
  if (¿Tiene capacitaciones registradas?) then (No)
    :Sistema muestra
    • Mensaje: "No tienes capacitaciones";
   
    
  else (Sí)
    :Sistema muestra dashboard completo;
    
    
    if (¿Postulante/Becario selecciona capacitación?) then (Sí)
      :Sistema muestra detalle específico;
      
      :Postulante/Becario solicita acceder a
      • Continuar donde lo dejó
      • Revisar material anterior
      • Ver retroalimentación
      • Descargar certificados;

      :Sistema permite acceder;
      
      if (¿Capacitación completada?) then (Sí)
        :Sistema permite
        • Descargar certificado
        • Ver calificación final
        • Acceder a material de referencia
        • Calificar la capacitación;
        
      else (No)
        :Sistema muestra
        • Siguiente actividad pendiente
        • Recordatorios de fechas límite
        • Progreso requerido para avanzar;
        
      endif
      
    endif
    
    :Postulante/Becario solicita generar reportes;

    :Sistema permite generar reportes;

    :Sistema genera reporte;
    
 
    
  endif
  
}

stop
@enduml