@startuml
skinparam actorStyle awesome
left to right direction
actor "Administrador" as Admin
actor "Seleccionador" as Seleccionador

rectangle "CRUD Postulante" {
  usecase "Crear Postulante" as CrearPostulante
  usecase "Listar Postulante" as ListarPostulante
  usecase "Editar Postulante" as EditarPostulante
  usecase "Eliminar Postulante" as EliminarPostulante
}

Admin --> CrearPostulante
Admin --> ListarPostulante
Admin --> EditarPostulante
Admin --> EliminarPostulante

Seleccionador --> ListarPostulante

@enduml