@startuml diagrama_contexto_postulante

skinparam {
    StateFontSize 14
    StateFontColor black
    StateBackgroundColor #f0f8ff
    StateBorderColor #4682b4
    ArrowColor #4682b4
    ArrowFontColor #191970
    ArrowFontSize 12
}

state "NO_AUTENTICADO" as NoAuth
state "MENU_PRINCIPAL" as Menu

state "CAPACITACIÓN" as Capacitacion {
    state "SELECCIÓN_CAPACITACIÓN" as SeleccionCap
    state "EN_CURSO" as EnCurso
    state "COMPLETADA" as Completada
    state "VER_PROGRESO" as VerProg
    
    [*] --> SeleccionCap : Listar las capacitaciones
    [*] --> VerProg : Ver progreso de las capacitaciones
    SeleccionCap --> EnCurso : Iniciar capacitación
    EnCurso --> Completada : Completar módulos
    EnCurso --> SeleccionCap : Sale de la capacitación sin finalizar
    Completada --> SeleccionCap : Seleccionar nueva\ncapacitación
}

[*] --> NoAuth

NoAuth --> Menu
    note on link
        Iniciar sesión
    end note

Menu --> NoAuth
    note on link
        Cerrar sesión
    end note

Menu --> Capacitacion
    note on link
        Realizar capacitación
    end note

Capacitacion --> Menu
    note on link
        Volver al menú
    end note

@enduml
