@startuml Actores_Sistema_Novus

skinparam actorStyle awesome

actor "POSTULANTE" as NoBecario
actor "BECARIO" as Becario
actor "Administrador de Aplicación" as AdminApp
actor "Seleccionador" as Seleccionador
actor "Usuario no registrado" as NoRegistrado

rectangle "Sistema Novus" {
}

NoBecario --> "Sistema Novus" : interactúa
Becario --> "Sistema Novus" : interactúa
AdminApp --> "Sistema Novus" : gestiona
Seleccionador --> "Sistema Novus" : supervisa
NoRegistrado --> "Sistema Novus" : interactúa

note right of NoBecario
  Postulantes que aún no han 
  aprobado los tests de selección
end note

note right of Becario
  Postulantes que han aprobado 
  los tests y cumplen los requisitos
end note

note right of AdminApp
  Personal encargado de la 
  gestión técnica de la plataforma
end note

note right of Seleccionador
  Personal de FUNIBER que recomienda 
  estudiantes para el programa PROFER
end note

note right of NoRegistrado
  Usuarios que no han accedido
  al sistema
end note


@enduml